### ISSUE TITLE
[Calendar] Сравнение дат

### ISSUE THREAD

**Issue by pavel-b-novikov** [MalafeevW/nsudotnet#1]
```number == DateTime.Now.Day && (resultDate.Month == DateTime.Now.Month) && (resultDate.Year == DateTime.Now.Year)```

Ну вы бы еще сюда минуты с секундами включили. 

как надо правильно сравнивать даты в .NET и почему?

**Comment by pavel-b-novikov** [comment]
Btw, вот это вот
```number == resultDate.Day```

Будет подсвечивать текущий день в ЛЮБОМ году

**Comment by MalafeevW** [comment]
number == DateTime.Now.Day && (resultDate.Month == DateTime.Now.Month) && (resultDate.Year == DateTime.Now.Year) исправил на resultDate == DateTime.Now
Мне кажется что несмотря на длинное сравнение год остался не учтённым, а простой и правильный способ бы всё учёл. Спасибо!
