### ISSUE TITLE
[NumberGuesser] Conventions

### ISSUE THREAD

**Issue by pavel-b-novikov** [MalafeevW/nsudotnet#10]
Прекратить, блджд, использовать camelCase для названий методов!

**Comment by MalafeevW** [comment]
Ок :-(

**Comment by pavel-b-novikov** [comment]
Ну и что ок? Где исправления?
Виталий, время позднее, у меня до черта работы помимо вас. Сейчас вы пойдете на следующий год.

**Comment by MalafeevW** [comment]
Во всех лабах исправлять?

**Comment by pavel-b-novikov** [comment]
Естественно, блин, во всех!
Потому что надо было ходить на лекции и слушать, когда я говорил о конвенциях в .NET

**Comment by pavel-b-novikov** [comment]
Настоящим сообщаю, что у вас осталось примерно полчаса чтобы исправить as much as possible и убедить меня поставить вам трояк

**Comment by MalafeevW** [comment]
Готово!

**Comment by pavel-b-novikov** [comment]
Да правда чтоли?
![image](https://cloud.githubusercontent.com/assets/2521412/26598939/02465c7c-45a1-11e7-9e29-b4b66e2ff0df.png)

**Comment by MalafeevW** [comment]
Исправил. Убедил? Извините за тот "Ок", не сразу понял о чем вы пока не загуглил.

**Comment by pavel-b-novikov** [comment]
Ну Serializer-то не исправлен

**Comment by pavel-b-novikov** [comment]
Окей
