### ISSUE TITLE
[JsonSerializer] null-ы и Non-Serialized

### ISSUE THREAD

**Issue by pavel-b-novikov** [MalafeevW/nsudotnet#6]
Сделайте так, чтобы null-поля тоже записывались в результат.

**Comment by MalafeevW** [comment]
Вобщем я понял что нужно null-ы не выкидывать как исключение, а обрабатывать и записывать их как Имя поля : null.

**Comment by pavel-b-novikov** [comment]
Ну вы молодец. Код-то где?

**Comment by MalafeevW** [comment]
Исправил, но забыл сюда отписать.

**Comment by MalafeevW** [comment]
Исправил конвенции в сериалтзере
