### ISSUE TITLE
[JsonSerializer] for

### ISSUE THREAD

**Issue by pavel-b-novikov** [MalafeevW/nsudotnet#7]
```for (var index = 0; index < fieldInfos.Length; index++)```

Переделайте на foreach.

**Comment by pavel-b-novikov** [comment]
И объясните как foreach работает

**Comment by MalafeevW** [comment]
Он применим к объектам класса, реализовывающего интерфейс System.Collections.Generic.IEnumerable<T>
IEnumerable это почти как Iterable в джаве, собственно через этот интерфейс и перебирает

**Comment by pavel-b-novikov** [comment]
Ну а детальнее? В какой код разворачивается foreach?

**Comment by MalafeevW** [comment]
Разворачивается в циклическое обращение к элементам коллекции. И для того чтобы массивы или нечто можно было рассматривать как коллекцию, то должен поддерживаться интерфейс IEnumerable. Вот пример кода:
using System;
using System.Collections;

namespace ConsoleApplication1
{
    class MyInt : IEnumerable, IEnumerator
    {
        int[] ints = { 12, 13, 1, 4 };
        int index = -1;

        // Реализуем интерфейс IEnumerable
        public IEnumerator GetEnumerator()
        {
            return this;
        }

        // Реализуем интерфейс IEnumerator
        public bool MoveNext()
        {
            if (index == ints.Length - 1)
            {
                Reset();
                return false;
            }

            index++;
            return true;
        }

        public void Reset()
        {
            index = -1;
        }

        public object Current
        {
            get
            {
                return ints[index];
            }
        }
    }

    class Program
    {
        static void Main()
        {
            MyInt mi = new MyInt();

            foreach (int i in mi)
                Console.Write(i+"\t");

            Console.ReadLine();
        }
    }
}

**Comment by pavel-b-novikov** [comment]
Еще раз вопрос.
Во что разворачивается вызов foreach?
Вот вы когда пишете foreach - компилятор его при компиляции переписывает в какой-то код. Вопрос - в какой?

**Comment by MalafeevW** [comment]
В такой:
IEnumerator<int> enumerator = Enumerable.Range(0, 128).GetEnumerator();
try
 {
   while (enumerator.MoveNext())
   {
     int item = enumerator.Current;
     Console.WriteLine(item);
   }
 }
finally
 {
  if (enumerator != null)
  {
   enumerator.Dispose();
  }
}
